config/routes.rb
Rails.application.routes.draw do
  ####################  contacts  ####################
  get '/contacts/index', to: 'contacts#index'
  get '/contacts/new', to: 'contacts#new'
  post '/contacts/new', to: 'contacts#create'
  ####################  likes  ########################
  post '/likes/:post_id/create', to: 'likes#create'
  delete '/likes/:post_id/destroy', to: 'likes#destroy'
  ####################  commnets  #####################
  post '/comments/new/:id', to: 'comments#create'
  ####################  posts  ########################
  get '/posts/index', to: 'posts#index'
  get '/posts/new', to: 'posts#new'
  post '/posts/new', to: 'posts#create'
  get '/posts/show/:id', to: 'posts#show'
  get '/posts/edit/:id', to: 'posts#edit'
  patch '/posts/edit/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#destroy'
  #################### home #######################
  get '/', to: 'home#top'
  get '/terms', to: 'home#terms_of_service'
  get '/policy', to: 'home#policy'
  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  #################################################
  post '/', to: 'users#create'
  ##################  Session  ####################
  patch '/', to:'sessions#create' #patchにしてるのはどうしても'/'が使いたいから
  delete '/logout', to:'sessions#destroy'
  ##################  users  #########################
  resources :users
  ###################  mail  ######################
  resources :account_activations, only:[:edit]
  ##################  password_reset  ###############
  resources :password_resets, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if current_user
      redirect_to current_user
    else
      @user = User.new
    end
  end

  def terms_of_service
  end

  def policy
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
ABOUT

app/views/home/help.html.erb
HELP

app/views/home/policy.html.erb
<div class="policy">
  <h1 class="title">プライバシーポリシー</h1>

  <p>サイト管理者（以下，「管理者」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）におけるプライバシー情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>

  <h3>第1条（プライバシー情報）</h3>

  <p>プライバシー情報のうち「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報を指します。</p>
  <p>プライバシー情報のうち「履歴情報および特性情報」とは，上記に定める「個人情報」以外のものをいい，ご利用いただいたサービスやご購入いただいた商品，ご覧になったページや広告の履歴，ユーザーが検索された検索キーワード，ご利用日時，ご利用の方法，ご利用環境，郵便番号や性別，職業，年齢，ユーザーのIPアドレス，クッキー情報，位置情報，端末の個体識別情報などを指します。</p>
  <h3>第２条（プライバシー情報の収集方法）</h3>

  <p>管理者は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や，決済に関する情報を管理者の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。</p>
  <p>管理者は，ユーザーについて，利用したサービスやソフトウエア，購入した商品，閲覧したページや広告の履歴，検索した検索キーワード，利用日時，利用方法，利用環境（携帯端末を通じてご利用の場合の当該端末の通信状態，利用に際しての各種設定情報なども含みます），IPアドレス，クッキー情報，位置情報，端末の個体識別情報などの履歴情報および特性情報を，ユーザーが管理者や提携先のサービスを利用しまたはページを閲覧する際に収集します。</p>
  <h3>第３条（個人情報を収集・利用する目的）</h3>

  <p>管理者が個人情報を収集・利用する目的は，以下のとおりです。</p>

  <p>（1）ユーザーに自分の登録情報の閲覧や修正，利用状況の閲覧を行っていただくために，氏名，住所，連絡先，支払方法などの登録情報，利用されたサービスや購入された商品，およびそれらの代金などに関する情報を表示する目的</p>
  <p>（2）ユーザーにお知らせや連絡をするためにメールアドレスを利用する場合やユーザーに商品を送付したり必要に応じて連絡したりするため，氏名や住所などの連絡先情報を利用する目的</p>
  <p>（3）ユーザーの本人確認を行うために，氏名，生年月日，住所，電話番号，銀行口座番号，クレジットカード番号，運転免許証番号，配達証明付き郵便の到達結果などの情報を利用する目的</p>
  <p>（4）ユーザーに代金を請求するために，購入された商品名や数量，利用されたサービスの種類や期間，回数，請求金額，氏名，住所，銀行口座番号やクレジットカード番号などの支払に関する情報などを利用する目的</p>
  <p>（5）ユーザーが簡便にデータを入力できるようにするために，管理者に登録されている情報を入力画面に表示させたり，ユーザーのご指示に基づいて他のサービスなど（提携先が提供するものも含みます）に転送したりする目的</p>
  <p>（6）代金の支払を遅滞したり第三者に損害を発生させたりするなど，本サービスの利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの利用をお断りするために，利用態様，氏名や住所など個人を特定するための情報を利用する目的</p>
  <p>（7）ユーザーからのお問い合わせに対応するために，お問い合わせ内容や代金の請求に関する情報など管理者がユーザーに対してサービスを提供するにあたって必要となる情報や，ユーザーのサービス利用状況，連絡先情報などを利用する目的</p>
  <p>（8）上記の利用目的に付随する目的</p>
  <h3>第４条（個人情報の第三者提供）</h3>

  <p>管理者は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</p>
  <p>（1）法令に基づく場合</p>
  <p>（2）人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</p>
  <p>（3）公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</p>
  <p>（4）国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</p>
  <p>（5）予め次の事項を告知あるいは公表をしている場合</p>
  <p>利用目的に第三者への提供を含むこと</p>
  <p>第三者に提供されるデータの項目</p>
  <p>第三者への提供の手段または方法</p>
  <p>本人の求めに応じて個人情報の第三者への提供を停止すること</p>
  <p>前項の定めにかかわらず，次に掲げる場合は第三者には該当しないものとします。</p>
  <p>（1）管理者が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</p>
  <p>（2）合併その他の事由による事業の承継に伴って個人情報が提供される場合</p>
  <p>（3）個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いているとき</p>
  <h3>第５条（個人情報の開示）</h3>

  <p>管理者は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，１件あたり8，０００円の手数料を申し受けます。</p>
  <p>（1）本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</p>
  <p>（2）管理者の業務の適正な実施に著しい支障を及ぼすおそれがある場合</p>
  <p>（3）その他法令に違反することとなる場合</p>
  <p>前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</p>
  <h3>第６条（個人情報の訂正および削除）</h3>

  <p>ユーザーは，管理者の保有する自己の個人情報が誤った情報である場合には，管理者が定める手続きにより，管理者に対して個人情報の訂正または削除を請求することができます。</p>
  <p>管理者は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正または削除を行い，これをユーザーに通知します。</p>
  <h3>第７条（個人情報の利用停止等）</h3>

  <p>管理者は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行い，その結果に基づき，個人情報の利用停止等を行い，その旨本人に通知します。ただし，個人情報の利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，本人の権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じます。</p>

  <h3>第８条（プライバシーポリシーの変更）</h3>

  <p>本ポリシーの内容は，ユーザーに通知することなく，変更することができるものとします。</p>
  <p>管理者が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</p>
</div>

app/views/home/terms_of_service.html.erb
<div class="terms_of_service">
  <h1 class="title">利用規約</h1>

  <p>この利用規約（以下，「本規約」といいます。）は，サイト管理者（以下，「管理者」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

  <h3>第1条（適用）</h3>

  <p>本規約は，ユーザーと管理者との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>

  <h3>第2条（利用登録）</h3>

  <p>登録希望者が管理者の定める方法によって利用登録を申請し，管理者がこれを承認することによって，利用登録が完了するものとします。</p>
  <p>管理者は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</p>
    <p>（1）利用登録の申請に際して虚偽の事項を届け出た場合</p>
    <p>（2）本規約に違反したことがある者からの申請である場合</p>
    <p>（3）未成年者，成年被後見人，被保佐人または被補助人のいずれかであり，法定代理人，後見人，保佐人または補助人の同意等を得ていなかった場合</p>
    <p>（4）反社会的勢力等（暴力団，暴力団員，右翼団体，反社会的勢力，その他これに準ずる者を意味します。）である，または資金提供その他を通じて反社会的勢力等の維持，運営もしくは経営に協力もしくは関与する等反社会的勢力との何らかの交流もしくは関与を行っていると管理者が判断した場合</p>
    <p>（5）その他，管理者が利用登録を相当でないと判断した場合</p>
  <h3>第3条（ユーザーIDおよびパスワードの管理）</h3>

  <p>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを管理するものとします。</p>
  <p>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与することはできません。管理者は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</p>

  <h3>第4条（禁止事項）</h3>

  <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>

  <p>（1）法令または公序良俗に違反する行為</p>
  <p>（2）犯罪行為に関連する行為</p>
  <p>（3）管理者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</p>
  <p>（4）管理者のサービスの運営を妨害するおそれのある行為</p>
  <p>（5）他のユーザーに関する個人情報等を収集または蓄積する行為</p>
  <p>（6）他のユーザーに成りすます行為</p>
  <p>（7）管理者のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</p>
  <p>（8）管理者，本サービスの他の利用者または第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</p>
  <p>（9）過度に暴力的な表現，露骨な性的表現，人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現，自殺，自傷行為，薬物乱用を誘引または助長する表現，その他反社会的な内容を含み他人に不快感を与える表現を，投稿または送信する行為</p>
  <p>（10）営業，宣伝，広告，勧誘，その他営利を目的とする行為（管理者の認めたものを除きます。），性行為やわいせつな行為を目的とする行為，面識のない異性との出会いや交際を目的とする行為，他のお客様に対する嫌がらせや誹謗中傷を目的とする行為，その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</p>
  <p>（11）宗教活動または宗教団体への勧誘行為</p>
  <p>（12）その他，管理者が不適切と判断する行為</p>
  <h3>第5条（本サービスの提供の停止等）</h3>

  <p>管理者は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</p>
  <p>（1）本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</p>
  <p>（2）地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</p>
  <p>（3）コンピュータまたは通信回線等が事故により停止した場合</p>
  <p>（4）その他，管理者が本サービスの提供が困難と判断した場合</p>
  <p>管理者は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。</p>
  <h3>第6条（著作権）</h3>

  <p>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報のみ，本サービスを利用し，投稿または編集することができるものとします。</p>
  <p>ユーザーが本サービスを利用して投稿または編集した文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，管理者は，本サービスを利用して投稿または編集された文章，画像，映像等を利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。</p>
  <p>前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他知的財産権はすべて管理者または管理者にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</p>
  <h3>第7条（利用制限および登録抹消）</h3>

  <p>管理者は，以下の場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。</p>
  <p>（1）本規約のいずれかの条項に違反した場合</p>
  <p>（2）登録事項に虚偽の事実があることが判明した場合</p>
  <p>（3）破産，民事再生，会社更生または特別清算の手続開始決定等の申立がなされたとき</p>
  <p>（4）1年間以上本サービスの利用がない場合</p>
  <p>（5）管理者からの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合</p>
  <p>（6）第2条第2項各号に該当する場合</p>
  <p>（7）その他，管理者が本サービスの利用を適当でないと判断した場合</p>
  <p>前項各号のいずれかに該当した場合，ユーザーは，当然に管理者に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</p>
  <p>管理者は，本条に基づき管理者が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</p>
  <h3>第8条（保証の否認および免責事項）</h3>

  <p>管理者は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</p>
  <p>管理者は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する管理者とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</p>
  <p>前項ただし書に定める場合であっても，管理者は，管理者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（管理者またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，管理者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</p>
  <p>管理者は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</p>
  <h3>第9条（サービス内容の変更等）</h3>

  <p>管理者は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>

  <h3>第10条（利用規約の変更）</h3>

  <p>管理者は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。</p>

  <h3>第11条（通知または連絡）</h3>

  <p>ユーザーと管理者との間の通知または連絡は，管理者の定める方法によって行うものとします。</p>

  <h3>第12条（権利義務の譲渡の禁止）</h3>

  <p>ユーザーは，管理者の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>

  <h3>第13条（準拠法・裁判管轄）</h3>

  <p>本規約の解釈にあたっては，日本法を準拠法とします。</p>
  <p>本サービスに関して紛争が生じた場合には，管理者の所在地を管轄する裁判所を専属的合意管轄とします。</p>
</div>

app/views/home/top.html.erb
<div class="top-container">
  <div class="error-modal">
    <%= render 'shared/error_messages' %>
  </div>
  <div class="top-text">
    <h1 class="title">Welcome <p>to the</p> <p>C-Bonds</p></h1>
    <div class="btn-wrapper">
      <div class="top-btn signup"><p>新規登録</p></div>
      <div class="top-btn signin"><p>ログイン</p></div>
    </div>
  </div>
  <div class="modal-top modal-signup">
    <div class="row">
      <span class="fa fa-times fa-2x"></span>
      <h1 class="title">新規登録</h1>
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user,url: '/') do |f| %>

          <%= f.label :name ,"ユーザー名"%>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email ,"メールアドレス"%>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password ,"パスワード"%>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "パスワード（確認用）" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <%= f.submit "アカウント作成", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal-top modal-signin">
    <span class="fa fa-times fa-2x"></span>
    <div class="row">
      <h1 class="title">ログイン</h1>
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(:session, url: '/', method: :patch) do |f| %>

          <%= f.label :email ,"Eメール"%>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password ,"パスワード"%>
          <%= link_to "忘れた方はこちら", new_password_reset_path %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span>ログイン情報を保持する</span>
          <% end %>

          <%= f.submit "送信", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="top-about">
  <div class="about-text textalign-center">
    <p><strong>C-Bondsとは</strong></p>
    <p>自分で作成した、作品を様々な人に見てもらいフィードバックをもらうためのwebアプリケーションです。</p>
    <p>フィードバックをもらえれば自分一人ではなかなか気づけない部分に触れることができます。</p>
    <p>完成した作品をどんどん投稿しましょう。</p>
  </div>
</div>

<script>
$(function(){
  $('.signup').click(function(){
    $('.modal-signup').fadeIn();
    $('.error-modal').hide();
    $('.modal-signin').hide();
  });
  $('.signin').click(function(){
    $('.modal-signin').fadeIn();
    $('.error-modal').hide();
    $('.modal-signup').hide();
  });
  $('.fa-times').click(function(){
    $('.modal-top').hide();
    $('.error-modal').hide();
  });

  
  });
</script>